### ISSUE TITLE
Internal Error when caseInsensitve parameter is not a terminal

### ISSUE THREAD

**Issue by rtoal** [harc/ohm#193] opened 2017-03-04 23:22 UTC
The grammar

```
Uhoh {
  c = caseInsensitive<"a".."z">
}
```

causes Ohm itself to fail with the stack trace

```
Uncaught Error: expected a Terminal expression
    at exports.assert (ohm.min.js:3)
    at CaseInsensitiveTerminal._getString (ohm.min.js:2)
    at CaseInsensitiveTerminal.eval (ohm.min.js:2)
    at MatchState.eval (ohm.min.js:3)
    at Apply.pexprs.Apply.evalOnce (ohm.min.js:4)
    at Apply.pexprs.Apply.reallyEval (ohm.min.js:4)
    at Apply.pexprs.Apply.eval (ohm.min.js:4)
    at MatchState.eval (ohm.min.js:3)
    at Seq.pexprs.Seq.eval (ohm.min.js:4)
    at MatchState.eval (ohm.min.js:3)
```

This causes the Ohm Editor to appear to hang.

**Comment by pdubroy** [comment] 2017-03-05 10:42
Hi Ray,

This is (mostly) working as intended. The `caseInsensitive` rule only works for literal strings and I think I'd like to keep it that way. Maybe we should consider making the error message easier to understand though.

If this is causing problems in the Ohm editor, that's another issue, and one that should definitely be fixed.

**Comment by pdubroy** [comment] 2017-03-05 10:47
I can't reproduce the problem with the editor. I see an error in the console, but if I continue to edit the grammar to fix the problem, everything is fine.

Are you trying the online version at https://ohmlang.github.io/editor/, or the latest from the ohm-editor repository?

**Comment by pdubroy** [comment] 2017-03-05 10:51
BTW I agree this looks an "internal error", but there is a certain class of runtime errors that can happen at grammar instantiation time, which are really errors for the grammar author. I'm thinking that we should figure out what all of those are (the one about nullable expressions in a repetition is another one), and clean those up so that they clearly indicate that the author did something wrong, as opposed to an internal error in Ohm. Maybe even with a URL that explains the error. What do you think?

**Comment by rtoal** [comment] 2017-03-05 17:24
Yes, I do that that this error should be surfaced to the user (the grammar author) somehow.

If I use the most recent version of the Ohm Editor, and I enter the following into the Grammar section:

```
C {
  c = "x
}
```

Then in the Ohm editor I see a big pink error box that says:

```
Line 2, col 9: expected "\""
```

So Ohm is telling me I did not write my grammar properly, and that I did not write my closing double quote after `x`. This is great. But let's say I make a slightly different mistake:

```
C {
  c = caseInsensitive<"a".."b">
}
```

At this point I have a mistake in my grammar but I get no pink box. I have no idea anything is wrong unless I look in the browser console. If I run from node I do the error, which is fine.

I see what you are saying, though, the second case is definitely a different kind of error, a static semantic error (my grammar follows the Ohm syntax but I did not use the parameterized rule properly), so it would take a bit of effort to surface that to the user the same way that the editor surfaces Ohm syntax errors (like the missing quote).

And yes, the Editor does continue to work after such errors... I only meant to point out the editor _appears to hang_ because we don't see a tree generated in the bottom panel. I suppose this is trying to tell me that I'm  in the middle of writing a grammar, but I really would expect to see an error in the Grammar panel, since something is wrong. 

I can see where this could get tricky.... What about user-defined parameterized rules with implicit semantic constraints? Should such things be allowed?

**Comment by pdubroy** [comment] 2017-03-06 08:49
Ok, thanks for the clarification. I think we are in agreement, the editor should definitely surface this to the user. The fact that it's doesn't was not a design choice, just an oversight.

I've opened up an issue in the ohm-editor repository for this.

Re:
> What about user-defined parameterized rules with implicit semantic constraints? Should such things be allowed?

Currently I don't think there's any way for a user to specify this, and I'm not sure we'd want to. `caseInsensitive` is kind of a special case because it needs a native implementation.

**Comment by pdubroy** [comment] 2017-03-06 08:51
Thanks for reporting this, Ray! I'll close this issue for now...further discussion about the UI can be done in the [ohm-editor issue](https://github.com/harc/ohm-editor/issues/29).

**Closed by pdubroy** 2017-03-06 08:51 UTC
