### ISSUE TITLE
Don't catch exceptions in semantics

### ISSUE THREAD

**Issue by JonathanMEdwards** [harc/ohm#198] opened 2017-04-01 17:16 UTC
Semantics.doit catches all exceptions thrown by semantics code in order to catch missingSemanticAction. This makes debugging exceptions in semantics very difficult, as the Node debugger loses the stack trace. Is there some way to avoid this?

**Comment by pdubroy** [comment] 2017-04-03 13:51
Yeah, I didn't think about that when I merged this. I have an idea for how to rewrite this to eliminate the try/catch -- will try to fix in the next day or two.

**Comment by pdubroy** [comment] 2017-04-04 15:16
I can't reproduce this on Node v6.1.0. But I believe that in some JS environments, catching an re-throwing an exception causes the original stack trace to be lost.

In any case, in c5d7046 I reworked the way we create the action stack traces, and user exceptions will no longer be caught and re-thrown, so this issue should be fixed regardless.

**Closed by pdubroy** 2017-04-04 15:16 UTC
